name: lf
channels:
  - conda-forge
dependencies:
  - llvmdev=11.1.0
  - toml
  - pytest
  - jupyter
  - xeus>=6.0.0
  - xeus-zmq>=4.0.0
  - nlohmann_json>=3.12.0
  - jupyter_kernel_test
  - xonsh=0.16.0
  - re2c
  - numpy
  - ninja
  - m2-bison=3.0.4
  - git
  - cmake
  - zlib
