/*
 * LFortran's ISO_Fortran_binding.h
 *
 * Implements the C descriptor types defined in Fortran 2018 subclause 18.5.
 * The struct layout matches LFortran's internal array descriptor as generated
 * by the LLVM codegen (see llvm_array_utils.cpp).
 *
 * Each Fortran compiler ships its own version of this header because the
 * standard leaves the descriptor layout implementation-defined.
 */

#ifndef CFI_ISO_FORTRAN_BINDING_H_
#define CFI_ISO_FORTRAN_BINDING_H_

#include <stddef.h>
#include <stdint.h>

#define CFI_VERSION 20180515
#define CFI_MAX_RANK 15

typedef unsigned char CFI_rank_t;
typedef ptrdiff_t CFI_index_t;
typedef unsigned char CFI_attribute_t;
typedef int16_t CFI_type_t;

#define CFI_attribute_pointer 1
#define CFI_attribute_allocatable 2
#define CFI_attribute_other 0

/* Type codes */
#define CFI_type_signed_char 1
#define CFI_type_short 2
#define CFI_type_int 3
#define CFI_type_long 4
#define CFI_type_long_long 5
#define CFI_type_size_t 6
#define CFI_type_int8_t 7
#define CFI_type_int16_t 8
#define CFI_type_int32_t 9
#define CFI_type_int64_t 10
#define CFI_type_float 27
#define CFI_type_double 28
#define CFI_type_long_double 30
#define CFI_type_float_Complex 34
#define CFI_type_double_Complex 35
#define CFI_type_Bool 39
#define CFI_type_char 40
#define CFI_type_cptr 41
#define CFI_type_struct 42
#define CFI_type_other (-1)

/* Error codes */
#define CFI_SUCCESS 0
#define CFI_ERROR_BASE_ADDR_NULL 11
#define CFI_ERROR_BASE_ADDR_NOT_NULL 12
#define CFI_INVALID_ELEM_LEN 13
#define CFI_INVALID_RANK 14
#define CFI_INVALID_TYPE 15
#define CFI_INVALID_ATTRIBUTE 16
#define CFI_INVALID_EXTENT 17
#define CFI_INVALID_DESCRIPTOR 18
#define CFI_ERROR_MEM_ALLOCATION 19
#define CFI_ERROR_OUT_OF_BOUNDS 20

/*
 * Per-dimension descriptor.
 *
 * LFortran's internal order is {stride, lower_bound, extent}.
 * We use the standard CFI names: sm (stride multiplier in bytes),
 * lower_bound, and extent.
 */
typedef struct CFI_dim_t {
    CFI_index_t sm;          /* stride multiplier in bytes */
    CFI_index_t lower_bound;
    CFI_index_t extent;      /* -1 for assumed size */
} CFI_dim_t;

/*
 * LFortran array descriptor — compatible with the LLVM IR struct
 * generated by llvm_array_utils.cpp:
 *
 *   { ptr, i64, i32, i8, i16, i8, i64, i1, [15 x {i64,i64,i64}] }
 *
 * The C compiler's natural alignment rules produce the same layout.
 */
typedef struct CFI_cdesc_t {
    void *base_addr;
    int64_t elem_len;
    int32_t version;
    int8_t rank;
    /* 1 byte padding (natural alignment for int16_t) */
    int16_t type;
    int8_t attribute;
    /* padding to align offset to 8 bytes */
    int64_t offset;
    uint8_t is_allocated;
    /* padding to align dim array to 8 bytes */
    CFI_dim_t dim[CFI_MAX_RANK];
} CFI_cdesc_t;

/* Storage macro for stack-allocated descriptors of a given rank */
#define CFI_CDESC_T(rank) CFI_cdesc_t

/* Minimal establish function (inline, no runtime library needed) */
static inline int CFI_establish(CFI_cdesc_t *desc, void *base_addr,
        CFI_attribute_t attribute, CFI_type_t type,
        size_t elem_len, CFI_rank_t rank,
        const CFI_index_t extents[]) {
    if (!desc) return CFI_INVALID_DESCRIPTOR;
    if (rank > CFI_MAX_RANK) return CFI_INVALID_RANK;
    desc->base_addr = base_addr;
    desc->elem_len = (int64_t)elem_len;
    desc->version = CFI_VERSION;
    desc->rank = (int8_t)rank;
    desc->type = type;
    desc->attribute = (int8_t)attribute;
    desc->offset = 0;
    desc->is_allocated = (base_addr != NULL);
    for (CFI_rank_t i = 0; i < rank; i++) {
        desc->dim[i].lower_bound = 0;
        desc->dim[i].extent = extents ? extents[i] : 0;
        desc->dim[i].sm = (CFI_index_t)elem_len;
        /* For contiguous arrays, sm = elem_len for dim 0,
           and elem_len * product(extents[0..i-1]) for dim i */
        for (CFI_rank_t j = 0; j < i; j++) {
            desc->dim[i].sm *= desc->dim[j].extent;
        }
    }
    return CFI_SUCCESS;
}

#endif /* CFI_ISO_FORTRAN_BINDING_H_ */
