name: lfortran_docs
channels:
  - conda-forge
dependencies:
  - lfortran=0.18.0
  - myst-parser=0.18.1
  - nbsphinx=0.8.10
  - sphinx=5.3.0
  - sphinx-intl=2.0.1
  - sphinx-copybutton=0.5.0
  - pip=22.3.1
  - lxml=4.9.1
  - unidecode=1.3.6
  - python-slugify=7.0.0
  - pip:
    - sphinx-material==0.0.35
