#!/usr/bin/env python3
"""Merge standalone integration test programs into a single program.

Compiling the integration tests dominates the cost of running them: on a
five-line program roughly 137 ms of a 179 ms `lfortran` invocation is process
startup, and the median test is 27 lines.  Merging N tests into one program
pays that startup once instead of N times.

A test file is laid out as

    [modules ...]
    program <name>
        <body>
    end program
    [external procedures / block data ...]

and is rewritten to

    [modules ...]
    [external procedures / block data ...]
    subroutine tc_<file stem>
        <body>
    end subroutine

with a generated driver calling every tc_* in turn.  Module names are already
unique across the suite (enforced by `run_tests.py -m`); program names are
not, so the subroutine name comes from the file stem.

Every test in one merged program must be compiled with the same flags, so the
caller is responsible for grouping by flag set.

Used by integration_tests/CMakeLists.txt at configure time, and runnable
standalone to check a grouping:

    ./merge_tests.py --output /tmp/merged.f90 intrinsics_01 intrinsics_02 ...
"""

import argparse
import os
import re
import sys

# `program foo`, on its own line, optionally with a trailing comment.
PROG_RE = re.compile(r'^[ \t]*program[ \t]+(\w+)[ \t]*(!.*)?$', re.IGNORECASE)
# `end program`, `end program foo`, likewise.
ENDPROG_RE = re.compile(r'^[ \t]*end[ \t]*program\b[ \t]*(\w+)?[ \t]*(!.*)?$',
                        re.IGNORECASE)


class Unsupported(Exception):
    """The file is not shaped like a mergeable test."""


def split_program(text):
    """Split a test source into (prelude, body, tail).

    prelude - everything before `program` (module definitions)
    body    - the main program's statements
    tail    - everything after `end program` (external procedures, block data)

    Raises Unsupported if the file is not a single `program` unit delimited by
    an explicit `end program`.
    """
    lines = text.split("\n")
    start = end = None
    for i, line in enumerate(lines):
        if start is None:
            if PROG_RE.match(line):
                start = i
        elif ENDPROG_RE.match(line):
            end = i
            break
    if start is None:
        raise Unsupported("no 'program NAME' statement on a line of its own")
    if end is None:
        raise Unsupported("no explicit 'end program' (bare 'end' is not enough)")
    for line in lines[end + 1:]:
        if PROG_RE.match(line):
            raise Unsupported("more than one program unit in the file")
    return ("\n".join(lines[:start]),
            "\n".join(lines[start + 1:end]),
            "\n".join(lines[end + 1:]))


def merge(paths, out_path, group="tests", trace=True):
    """Write a merged program for `paths`.  Returns the list of test stems."""
    preludes, subroutines, stems = [], [], []
    for path in paths:
        stem = os.path.splitext(os.path.basename(path))[0]
        with open(path, encoding="utf-8", errors="replace") as f:
            text = f.read()
        try:
            prelude, body, tail = split_program(text)
        except Unsupported as e:
            raise Unsupported("%s: %s" % (os.path.basename(path), e))
        if prelude.strip():
            preludes.append((stem, prelude.rstrip()))
        # Hoist trailing external procedures next to the modules: they are
        # top-level program units and must not end up inside the subroutine.
        if tail.strip():
            preludes.append((stem, tail.rstrip()))
        subroutines.append((stem, body.rstrip()))
        stems.append(stem)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("! Generated by merge_tests.py -- do not edit.\n")
        f.write("! Merged group '%s': %d tests.\n" % (group, len(stems)))
        f.write("! Each test keeps its own source file; this file only changes\n")
        f.write("! how they are compiled.  See integration_tests/merge_tests.py.\n\n")
        for stem, text in preludes:
            f.write("! ---- from %s.f90 ----\n%s\n\n" % (stem, text))
        for stem, body in subroutines:
            f.write("subroutine tc_%s\n%s\nend subroutine tc_%s\n\n"
                    % (stem, body, stem))
        f.write("program merged_%s\n" % group)
        for stem in stems:
            if trace:
                # Breadcrumb on stderr: when one test aborts the whole program,
                # this is what names it.  ctest shows it via --output-on-failure.
                f.write('    write(0,*) "[RUN] %s"\n' % stem)
            f.write("    call tc_%s\n" % stem)
        f.write('    write(0,*) "[ALL PASSED] %d tests"\n' % len(stems))
        f.write("end program merged_%s\n" % group)
    return stems


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--output", required=True, help="merged source to write")
    p.add_argument("--group", default="tests", help="group name")
    p.add_argument("--source-dir", default=".", help="where the test sources live")
    p.add_argument("--list-file", help="file holding one test name per line")
    p.add_argument("--no-trace", action="store_true",
                   help="omit the per-test stderr breadcrumbs")
    p.add_argument("tests", nargs="*", help="test names, without the .f90 suffix")
    args = p.parse_args()

    names = list(args.tests)
    if args.list_file:
        with open(args.list_file) as f:
            names += [l.strip() for l in f if l.strip()]
    if not names:
        p.error("no tests given")

    paths = [os.path.join(args.source_dir, n + ".f90") for n in names]
    missing = [p_ for p_ in paths if not os.path.exists(p_)]
    if missing:
        sys.stderr.write("merge_tests.py: missing sources: %s\n"
                         % ", ".join(missing))
        return 1
    try:
        stems = merge(paths, args.output, group=args.group,
                      trace=not args.no_trace)
    except Unsupported as e:
        sys.stderr.write("merge_tests.py: cannot merge %s\n" % e)
        return 1
    sys.stderr.write("merge_tests.py: %s <- %d tests\n"
                     % (os.path.basename(args.output), len(stems)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
