SUBROUTINE extfun (FUN)
IMPLICIT NONE
REAL  X1, X, H
REAL G8, FUN
! Note: do not convert it to lower case, issue is with `G8` being in upper case
G8(X,H)=X-X1*H
FUN=G8(123.0,29.025)
END

PROGRAM STATEMENT_FUNCTION_01
IMPLICIT NONE
REAL FUN
CALL extfun(FUN)
PRINT *, FUN
IF ( ABS( FUN - 123.000000 ) > 1e-8 ) ERROR STOP
END PROGRAM
