SUBROUTINE DVOUT()
   CHARACTER*80       LINE
9999 FORMAT( / 1X, A, / 1X, A )
   LOUT = 10
   WRITE( LOUT, FMT = 9999 )IFMT, LINE( 1: LLL )
END SUBROUTINE

PROGRAM WRITE_03
   CALL DVOUT()
END PROGRAM


