#!/usr/bin/env bash

set -ex

# Generate the version, parser, tokenizer and AST from the ASDL files.
mkdir "tarball"
pushd "tarball"
cmake ..
popd
rm -rf "tarball"

# By default, set the tarball version to version generated by CMake.
lfortran_version=$(<version)
# Optionally, override the default version with a cmdline argument.
if [ $# -eq 1 ]; then
    lfortran_version=$1
fi
dest=lfortran-$lfortran_version

cmake -E make_directory $dest

# Copy Directories:
cmake -E copy_directory src $dest/src
cmake -E copy_directory share $dest/share
cmake -E copy_directory cmake $dest/cmake
cmake -E copy_directory examples $dest/examples

# Copy Files:
cmake -E copy CMakeLists.txt README.md LICENSE version $dest

# Create the tarball
cmake -E make_directory dist
cmake -E tar cfz dist/$dest.tar.gz $dest
cmake -E remove_directory $dest
