execute_process(
  COMMAND "${CMAKE_COMMAND}"
  "-G ${CMAKE_GENERATOR}"
  "-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}"
  "-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}"
  "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
  "-DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}"
  "-DCMAKE_VERBOSE_MAKEFILE:BOOL=${CMAKE_VERBOSE_MAKEFILE}"
  "-DCMAKE_Fortran_COMPILER=${CMAKE_INSTALL_PREFIX}/bin/lfortran"
  "-DWITH_RUNTIME_LIBRARY=${WITH_RUNTIME_LIBRARY}"
  "${CMAKE_SOURCE_DIR}/src/runtime/"
  WORKING_DIRECTORY "${CMAKE_BINARY_DIR}/src/runtime"
  RESULT_VARIABLE STATUS_CONFIGURE
  COMMAND_ECHO STDOUT)

if (STATUS_CONFIGURE AND NOT STATUS_CONFIGURE EQUAL 0)
  message(FATAL_ERROR "cmake failed with status: ${STATUS_CONFIGURE}")
else()
  message(STATUS "Done.")
endif()

execute_process(
  COMMAND "${CMAKE_COMMAND}" --build . --target install
  WORKING_DIRECTORY "${CMAKE_BINARY_DIR}/src/runtime"
  RESULT_VARIABLE STATUS_BUILD
  COMMAND_ECHO STDOUT)

if (STATUS_BUILD AND NOT STATUS_BUILD EQUAL 0)
  message(FATAL_ERROR "cmake failed with status: ${STATUS_BUILD}")
else()
  message(STATUS "Done.")
endif()
