include(Compiler/Clang)

set(CMAKE_Fortran_SUBMODULE_SEP "-")
set(CMAKE_Fortran_SUBMODULE_EXT ".mod")

set(CMAKE_Fortran_FORMAT_FIXED_FLAG "--fixed-form")
set(CMAKE_Fortran_FORMAT_FREE_FLAG "")

set(CMAKE_Fortran_MODDIR_FLAG "-J")

set(CMAKE_Fortran_COMPILE_OPTIONS_PREPROCESS_ON "--cpp")
set(CMAKE_Fortran_COMPILE_OPTIONS_PREPROCESS_OFF "")

set(CMAKE_Fortran_COMPILE_OBJECT "<CMAKE_Fortran_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -c <SOURCE> -o <OBJECT>")
# set(CMAKE_Fortran_CREATE_SHARED_LIBRARY )
# set(CMAKE_Fortran_CREATE_SHARED_MODULE )
# set(CMAKE_Fortran_CREATE_STATIC_LIBRARY )
# set(CMAKE_Fortran_COMPILE_OBJECT )
# set(CMAKE_Fortran_LINK_EXECUTABLE )

set(CMAKE_Fortran_PREPROCESS_SOURCE "<CMAKE_Fortran_COMPILER> --cpp <DEFINES> <INCLUDES> <FLAGS> -E <SOURCE> > <PREPROCESSED_SOURCE>")

# set(CMAKE_Fortran_INFORMATION_LOADED 1)
# set(CMAKE_Fortran_COMPILER_WORKS 1 CACHE INTERNAL "")
